services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    environment:
      - NODE_ENV=development
      - PORT=3000
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
