networks:
  app-network:
    driver: bridge

services:
  app:
    build:
      context: .
      target: dev
    environment:
      - NODE_ENV=development
      - PORT=3000
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    networks:
      - app-network

  nginx:
    image: jwilder/nginx-proxy
    container_name: nginx
    ports:
      - "80:80"   
      - "443:443" 
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app-network
    restart: always 
    depends_on:
      - app
    
  app-prod: 
    build:
      context: .
      target: prod
    environment:
      - NODE_ENV=production
      - PORT=4000
    ports:
      - '4000:4000' 
    volumes:
      - ./database.sqlite:/app/database.sqlite
    command: npm run start